name: Our.Umbraco.Forms.Mailcoach - CI

on:
  pull_request:

env:
  SOLUTION: Our.Umbraco.Forms.Mailcoach.sln
  OUTPUT_PATH: ${{ github.workspace }}/.output

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['8.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3

      with:
        dotnet-version: ${{ matrix.dotnet-version }}
  
    - name: Install dependencies
      run: dotnet restore Our.Umbraco.Forms.Mailcoach.Release.sln
  
    - name: Build
      run: dotnet build Our.Umbraco.Forms.Mailcoach.Release.sln --configuration Release --no-restore
        
    - name: Create the package
      run: dotnet pack Our.Umbraco.Forms.Mailcoach.Release.sln --configuration Release -o ${{ env.OUTPUT_PATH }}
      
    - name: Upload NuGet artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: ${{ env.OUTPUT_PATH }}
